# Firewall API status codes
CERTIFICATE_UPDATED_SUCCESSFULLY = 200
CERTIFICATE_ADDED_SUCCESSFULLY = 200
CERTIFICATE_NOT_FOUND = 500
CERTIFICATE_COULD_NOT_BE_GENERATED = 500
CERTIFICATE_ALREADY_EXISTS = 502
